/*
 *
 * Formulario ventana Registro
 * 
 */
package ventanaregistrarse;

//Librerias
import ConexioOracle.Conexion;
import VentanaLogin.Login;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * @author Napster Guerlmy Alexander Nuñez Matricula 2021-0466
 */
public class Registrarse extends javax.swing.JFrame {

    /**
     * Creates new form Registrarse
     */
    public Registrarse() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/pokeball.png")).getImage());
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRegistro = new javax.swing.JPanel();
        btnRegistrarRegistro = new javax.swing.JToggleButton();
        btnRegresarRegistro = new javax.swing.JToggleButton();
        lbNombreusuario1 = new javax.swing.JLabel();
        txtNombreUsuarioRegistro = new javax.swing.JTextField();
        lbPassword = new javax.swing.JLabel();
        passPasswordRegistro = new javax.swing.JPasswordField();
        lbRepetirPassword = new javax.swing.JLabel();
        passRepetirPasswordRegistro = new javax.swing.JPasswordField();
        lbPrimerNombre = new javax.swing.JLabel();
        txtPrimerNombreRegistro = new javax.swing.JTextField();
        lbSegundoNombre = new javax.swing.JLabel();
        txtSegundoNombreRegistro = new javax.swing.JTextField();
        lbPrimerApellido = new javax.swing.JLabel();
        txtPrimerApellidoRegistro = new javax.swing.JTextField();
        lbSegundoApellido = new javax.swing.JLabel();
        txtSegundoApellidoRegistro = new javax.swing.JTextField();
        lbNumeroCell = new javax.swing.JLabel();
        txtNumeroCellRegistro = new javax.swing.JTextField();
        CorreoElectronico = new javax.swing.JLabel();
        txtCorreoElectronicoRegistro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbFondoRegistro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pokemon Trainer Register");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrarRegistro.setText("Registrar");
        btnRegistrarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarRegistroActionPerformed(evt);
            }
        });
        jPanelRegistro.add(btnRegistrarRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, 170, 40));

        btnRegresarRegistro.setText("Regresar");
        btnRegresarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarRegistroActionPerformed(evt);
            }
        });
        jPanelRegistro.add(btnRegresarRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 450, 170, 40));

        lbNombreusuario1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbNombreusuario1.setForeground(new java.awt.Color(255, 255, 255));
        lbNombreusuario1.setText("Nombre Usuario");
        jPanelRegistro.add(lbNombreusuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 130, 30));

        txtNombreUsuarioRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreUsuarioRegistroActionPerformed(evt);
            }
        });
        jPanelRegistro.add(txtNombreUsuarioRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 350, -1));

        lbPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbPassword.setForeground(new java.awt.Color(255, 255, 255));
        lbPassword.setText("Password");
        jPanelRegistro.add(lbPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 130, 30));

        passPasswordRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passPasswordRegistroActionPerformed(evt);
            }
        });
        jPanelRegistro.add(passPasswordRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 350, -1));

        lbRepetirPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbRepetirPassword.setForeground(new java.awt.Color(255, 255, 255));
        lbRepetirPassword.setText("Repetir Password");
        jPanelRegistro.add(lbRepetirPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 140, 30));
        jPanelRegistro.add(passRepetirPasswordRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 350, -1));

        lbPrimerNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbPrimerNombre.setForeground(new java.awt.Color(255, 255, 255));
        lbPrimerNombre.setText("Primer Nombre");
        jPanelRegistro.add(lbPrimerNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 140, 30));

        txtPrimerNombreRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrimerNombreRegistroActionPerformed(evt);
            }
        });
        jPanelRegistro.add(txtPrimerNombreRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 350, -1));

        lbSegundoNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbSegundoNombre.setForeground(new java.awt.Color(255, 255, 255));
        lbSegundoNombre.setText("Segundo Nombre");
        jPanelRegistro.add(lbSegundoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 140, 30));

        txtSegundoNombreRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSegundoNombreRegistroActionPerformed(evt);
            }
        });
        jPanelRegistro.add(txtSegundoNombreRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 350, -1));

        lbPrimerApellido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbPrimerApellido.setForeground(new java.awt.Color(255, 255, 255));
        lbPrimerApellido.setText("Primer Apellido");
        jPanelRegistro.add(lbPrimerApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 140, 30));

        txtPrimerApellidoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrimerApellidoRegistroActionPerformed(evt);
            }
        });
        jPanelRegistro.add(txtPrimerApellidoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 350, -1));

        lbSegundoApellido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbSegundoApellido.setForeground(new java.awt.Color(255, 255, 255));
        lbSegundoApellido.setText("Segundo Apellido");
        jPanelRegistro.add(lbSegundoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 140, 30));

        txtSegundoApellidoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSegundoApellidoRegistroActionPerformed(evt);
            }
        });
        jPanelRegistro.add(txtSegundoApellidoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 350, -1));

        lbNumeroCell.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbNumeroCell.setForeground(new java.awt.Color(255, 255, 255));
        lbNumeroCell.setText("Numero Cell");
        jPanelRegistro.add(lbNumeroCell, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 140, 30));

        txtNumeroCellRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroCellRegistroActionPerformed(evt);
            }
        });
        jPanelRegistro.add(txtNumeroCellRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 350, -1));

        CorreoElectronico.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CorreoElectronico.setForeground(new java.awt.Color(255, 255, 255));
        CorreoElectronico.setText("Correo Electronico");
        jPanelRegistro.add(CorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 150, 30));

        txtCorreoElectronicoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoElectronicoRegistroActionPerformed(evt);
            }
        });
        jPanelRegistro.add(txtCorreoElectronicoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 350, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("*");
        jPanelRegistro.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 40, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("*");
        jPanelRegistro.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 40, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("*");
        jPanelRegistro.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 40, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("*");
        jPanelRegistro.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 40, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("*");
        jPanelRegistro.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 40, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("*");
        jPanelRegistro.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 40, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("*");
        jPanelRegistro.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 40, -1));

        lbFondoRegistro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbFondoRegistro.setForeground(new java.awt.Color(255, 255, 255));
        lbFondoRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo resgistro.jpg"))); // NOI18N
        jPanelRegistro.add(lbFondoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        getContentPane().add(jPanelRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreUsuarioRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreUsuarioRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUsuarioRegistroActionPerformed

    private void txtPrimerNombreRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrimerNombreRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrimerNombreRegistroActionPerformed

    private void txtSegundoNombreRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSegundoNombreRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSegundoNombreRegistroActionPerformed

    private void txtPrimerApellidoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrimerApellidoRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrimerApellidoRegistroActionPerformed

    private void txtSegundoApellidoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSegundoApellidoRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSegundoApellidoRegistroActionPerformed

    private void txtNumeroCellRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroCellRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroCellRegistroActionPerformed

    private void txtCorreoElectronicoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoElectronicoRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoElectronicoRegistroActionPerformed

    private void btnRegresarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarRegistroActionPerformed
        //El boton regresar nos devolvera al Login y cerrara esta ventana
        Login formularioLogin = new Login();
        formularioLogin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarRegistroActionPerformed

    private void btnRegistrarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarRegistroActionPerformed

        //Si los campos son validados correctamente capturamos los datos
        if (ValidarCampos()) {
            String usuario = txtNombreUsuarioRegistro.getText();
            String clave = String.valueOf(passPasswordRegistro.getPassword());
            String nombre1 = txtPrimerNombreRegistro.getText();
            String nombre2 = txtSegundoNombreRegistro.getText();
            String apellido1 = txtPrimerApellidoRegistro.getText();
            String apellido2 = txtSegundoApellidoRegistro.getText();
            String numeroTel = txtNumeroCellRegistro.getText();
            String correoElectronico = txtCorreoElectronicoRegistro.getText();

            //Dentro del Try/Catch haremos el INSERT para registrar el nuevo usuario
            try {
                Connection con;
                con = Conexion.getConnection();
                PreparedStatement preparaConsulta = con.prepareStatement("INSERT INTO usuarios (nombre_usuario, clave, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, numero_telefono, email) VALUES (?,?,?,?,?,?,?,?)");
                preparaConsulta.setString(1, usuario);
                preparaConsulta.setString(2, clave);
                preparaConsulta.setString(3, nombre1);
                preparaConsulta.setString(4, nombre2);
                preparaConsulta.setString(5, apellido1);
                preparaConsulta.setString(6, apellido2);
                preparaConsulta.setString(7, numeroTel);
                preparaConsulta.setString(8, correoElectronico);

                preparaConsulta.execute();

                //Luego de haber ejecutado correctamente la consulta hacemos el commit y cerramos la conexion
                con.commit();
                con.close();

                //ejecutamos el metodo Limpiar() para dejar el formulario listo para otro registro
                Limpiar();
                JOptionPane.showMessageDialog(null, "EL USUARIO FUE REGISTRADO CON EXITO");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "EL USUARIO NO ESTA DISPONIBLE INTENTE CON OTRO");
            }

        }


    }//GEN-LAST:event_btnRegistrarRegistroActionPerformed

    private void passPasswordRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passPasswordRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passPasswordRegistroActionPerformed

    //Metodo para velidar todos los campos 
    public boolean ValidarCampos() {

        boolean camposValidados = false;

        if (txtNombreUsuarioRegistro.getText().length() != 0) {
            if (String.valueOf(passPasswordRegistro.getPassword()).length() != 0) {
                if (String.valueOf(passRepetirPasswordRegistro.getPassword()).length() != 0) {
                    if (txtPrimerNombreRegistro.getText().length() != 0) {
                        if (txtPrimerApellidoRegistro.getText().length() != 0) {
                            if (txtNumeroCellRegistro.getText().length() != 0) {
                                if (txtCorreoElectronicoRegistro.getText().length() != 0) {
                                    if (String.valueOf(passPasswordRegistro.getPassword()).equals(String.valueOf(passRepetirPasswordRegistro.getPassword()))) {
                                        camposValidados = true;
                                    } else {
                                        JOptionPane.showMessageDialog(null, "Los Campos de Password y Repetir Password \n No Coinciden");
                                    }
                                } else {
                                    JOptionPane.showMessageDialog(null, "El Campo Correo Electronico Esta Vacio");
                                }

                            } else {
                                JOptionPane.showMessageDialog(null, "El Campo Numero De Telefono Esta Vacio");
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "El Campo Primer Apellido Esta Vacio");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "El Campo Primer Nombre Esta Vacio");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El Campo Repetir Password Esta Vacio");
                }
            } else {
                JOptionPane.showMessageDialog(null, "El Campo Password Esta Vacio");
            }
        } else {
            JOptionPane.showMessageDialog(null, "El Campo Usuario Esta Vacio");
        }
        return camposValidados;
    }

    //metodo para limpiar los campos
    public void Limpiar() {
        txtNombreUsuarioRegistro.setText("");
        passPasswordRegistro.setText("");
        passRepetirPasswordRegistro.setText("");
        txtPrimerNombreRegistro.setText("");
        txtSegundoNombreRegistro.setText("");
        txtPrimerApellidoRegistro.setText("");
        txtSegundoApellidoRegistro.setText("");
        txtNumeroCellRegistro.setText("");
        txtCorreoElectronicoRegistro.setText("");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrarse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CorreoElectronico;
    private javax.swing.JToggleButton btnRegistrarRegistro;
    private javax.swing.JToggleButton btnRegresarRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanelRegistro;
    private javax.swing.JLabel lbFondoRegistro;
    private javax.swing.JLabel lbNombreusuario1;
    private javax.swing.JLabel lbNumeroCell;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbPrimerApellido;
    private javax.swing.JLabel lbPrimerNombre;
    private javax.swing.JLabel lbRepetirPassword;
    private javax.swing.JLabel lbSegundoApellido;
    private javax.swing.JLabel lbSegundoNombre;
    private javax.swing.JPasswordField passPasswordRegistro;
    private javax.swing.JPasswordField passRepetirPasswordRegistro;
    private javax.swing.JTextField txtCorreoElectronicoRegistro;
    private javax.swing.JTextField txtNombreUsuarioRegistro;
    private javax.swing.JTextField txtNumeroCellRegistro;
    private javax.swing.JTextField txtPrimerApellidoRegistro;
    private javax.swing.JTextField txtPrimerNombreRegistro;
    private javax.swing.JTextField txtSegundoApellidoRegistro;
    private javax.swing.JTextField txtSegundoNombreRegistro;
    // End of variables declaration//GEN-END:variables
}
