/*
 * Clase que contiene el formulario login
 * la ventana de inicio cel programa 
 */
package VentanaLogin;

//Importamos la libreria JDBC necesarias 
import ConexioOracle.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import ventanaPrincipal.VentanaPrincipal;
import ventanaregistrarse.Registrarse;

/**
 *
 * @author Napster Guerlmy Alexander Nuñez Matricula 2021-0466
 */
//Clase Login que hereda de JSwing
public class Login extends javax.swing.JFrame {

    //Metodo constructor que inicializa el formulario
    public Login() {
        initComponents();

        //Con esta linea obtenemos una imagen que esta en el directorio imagenes con su extension  
        //y la colocamos en la barra de titulo
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/pokeball.png")).getImage());

        //Para colocar el formulario al iniciar en el centro de la pantalla del monitor
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbUsuario = new javax.swing.JLabel();
        lbPassword = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JToggleButton();
        btnRegistrarse1 = new javax.swing.JToggleButton();
        btnSalirLogin = new javax.swing.JToggleButton();
        txtUsuarioLogin = new javax.swing.JTextField();
        passClaveLogin = new javax.swing.JPasswordField();
        lbMarca = new javax.swing.JLabel();
        fondoLogin = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Poke Usuario");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbUsuario.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        lbUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lbUsuario.setText("Password");
        getContentPane().add(lbUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 90, 20));

        lbPassword.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        lbPassword.setForeground(new java.awt.Color(255, 255, 255));
        lbPassword.setText("User");
        getContentPane().add(lbPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 90, 20));

        btnIngresar.setBackground(new java.awt.Color(0, 51, 204));
        btnIngresar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 290, 40));

        btnRegistrarse1.setBackground(new java.awt.Color(0, 51, 204));
        btnRegistrarse1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRegistrarse1.setText("Registarse");
        btnRegistrarse1.setPreferredSize(new java.awt.Dimension(73, 23));
        btnRegistrarse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarse1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarse1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 290, 40));

        btnSalirLogin.setBackground(new java.awt.Color(0, 51, 204));
        btnSalirLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSalirLogin.setText("Salir");
        btnSalirLogin.setPreferredSize(new java.awt.Dimension(73, 23));
        btnSalirLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalirLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 290, 40));

        txtUsuarioLogin.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtUsuarioLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioLoginActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuarioLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 340, 30));

        passClaveLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passClaveLoginActionPerformed(evt);
            }
        });
        getContentPane().add(passClaveLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 340, 30));

        lbMarca.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbMarca.setText("Napster Corp® and The Pokemon Company® ");
        getContentPane().add(lbMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 290, -1));

        fondoLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fondoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(fondoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioLoginActionPerformed

    private void passClaveLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passClaveLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passClaveLoginActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed

        //El boton ingresar tendra las siguientes acciones
        //Capturamos el texto introducido en la caja de texto y en la caja de password
        String nombreUsuario = txtUsuarioLogin.getText();
        String clave = String.valueOf(passClaveLogin.getPassword());

        //Para hacer las consultas SQL usamos el PreparedStatement y el ResultSet
        PreparedStatement prepararConsulta;
        ResultSet resultado;

        //Condicion para validar los posibles casos
        //1ero: si ambos campos estan vacios
        if (nombreUsuario.length() == 0 && clave.length() == 0) {
            JOptionPane.showMessageDialog(null, "DIGITE SU USUARIO Y SU PASSWORD");

            //2do: si el campo usuario esta vacio
        } else if (nombreUsuario.length() == 0) {
            JOptionPane.showMessageDialog(null, "DIGITE SU USUARIO");

            //3ro: si el campo password esta vacio
        } else if (clave.length() == 0) {
            JOptionPane.showMessageDialog(null, "DIGITE SU PASSWORD");

        } else {

            // Si todos los campos estan llenos intentara hacer la coneccion dentro de un Try/Catch
            try {

                //Declaramos el objeto conn de tipo Connection
                Connection conn;

                //En este objeto archivamos la conexion usando el metodo getConnection() 
                //de la clase conexion de Oracle que cree
                conn = Conexion.getConnection();

                //Con el PreparedStatement hacemos la consulta para comprobar 
                //si el usuario y password estan en la base de datos 
                prepararConsulta = conn.prepareStatement("SELECT * FROM usuarios WHERE nombre_usuario = ? and clave = ?");
                prepararConsulta.setString(1, nombreUsuario);
                prepararConsulta.setString(2, clave);

                //Luego de tener la consulta preparada la ejecutamos y guardamos en el ResultSet
                resultado = prepararConsulta.executeQuery();

                //Si el usuario existe ejecutamos el metodo .next() de la clases ResultSet
                //que debe dar un valor boolean = a true
                if (resultado.next()) {
                    //Mensaje que da la bienvenida al usuario
                    JOptionPane.showMessageDialog(null, "Bienvenido " + nombreUsuario.toUpperCase());

                    //Abrimos el formulario que representa la ventana principal y cerramos esta clase
                    VentanaPrincipal formularioPrincipal = new VentanaPrincipal();
                    formularioPrincipal.setVisible(true);
                    this.setVisible(false);
                } else {
                    //Si el usuario no esta registrado mandara este mensaje
                    JOptionPane.showMessageDialog(null, "Usuario no Registrado \n Usuario y Password Invalidos no Coinciden");

                }
                //luego ceeramos la coneccion 
                conn.close();

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e.toString());
            }

        }


    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnSalirLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirLoginActionPerformed
        //El boton salir simplemente tumba la ejecucion con el metodo exit
        System.exit(0);
    }//GEN-LAST:event_btnSalirLoginActionPerformed

    private void btnRegistrarse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarse1ActionPerformed
        //El boton registrar abre la ventana de registro y cierra el formulario de login
        Registrarse formularioRegistrarse = new Registrarse();
        formularioRegistrarse.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegistrarse1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnIngresar;
    private javax.swing.JToggleButton btnRegistrarse1;
    private javax.swing.JToggleButton btnSalirLogin;
    private javax.swing.JLabel fondoLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbMarca;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JPasswordField passClaveLogin;
    private javax.swing.JTextField txtUsuarioLogin;
    // End of variables declaration//GEN-END:variables
}
